# Generated by Django 4.1.4 on 2023-02-03 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField(db_column='Amount')),
                ('tracking_id', models.CharField(blank=True, db_column='TrackingID', max_length=31, null=True)),
                ('trx', models.CharField(blank=True, db_column='trx', max_length=31, null=True)),
                ('card_number', models.CharField(blank=True, db_column='CardNumber', max_length=31, null=True)),
                ('is_successful', models.BooleanField(db_column='IsSuccessful', default=False)),
                ('raw_date', models.JSONField(blank=True, db_column='RawData', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('order_id', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.PROTECT, to='card.order')),
                ('user_id', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
    ]
