# Generated by Django 4.1.4 on 2022-12-30 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('raw_date', models.JSONField()),
                ('buy_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.buy')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.wallet')),
            ],
        ),
    ]
