# Generated by Django 4.1.4 on 2023-01-20 19:23

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(db_column='Cover', default='', upload_to=blog.models.Blog.blog_covers_path),
            preserve_default=False,
        ),
    ]
