# Generated by Django 4.1.4 on 2023-01-27 20:24

import card.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(db_column='Image', upload_to=card.models.Card.card_images_path)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('min_amount', models.PositiveIntegerField(db_column='MinAmount')),
                ('max_amount', models.PositiveIntegerField(db_column='MaxAmount')),
            ],
            options={
                'db_table': 'Card',
            },
        ),
        migrations.CreateModel(
            name='PurchasedCard',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('owner_phone_number', models.CharField(db_column='OwnerPhoneNumber', max_length=31)),
                ('btc_amount', models.FloatField(db_column='BTCAmount')),
                ('code', models.CharField(db_column='Code', max_length=31)),
                ('cost', models.PositiveBigIntegerField(db_column='Cost', help_text='Toman')),
                ('message', models.CharField(db_column='Message', default='', help_text='Text of the message', max_length=511)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('card_id', models.ForeignKey(db_column='CardID', on_delete=django.db.models.deletion.PROTECT, to='card.card')),
                ('previous_owner', models.ForeignKey(db_column='PreviousOwner', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PurchasedCard',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Processing'), (2, 'Creating Wallet'), (3, 'Charging Wallet'), (4, 'Posting'), (5, 'Received'), (6, 'Confirmed')], db_column='State')),
                ('receiver_name', models.CharField(db_column='ReceiverName', max_length=63)),
                ('receiver_phone_number', models.CharField(db_column='ReceiverPhoneNumber', max_length=31)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('address_id', models.ForeignKey(db_column='AddressID', on_delete=django.db.models.deletion.PROTECT, to='user.address')),
                ('card_id', models.ForeignKey(db_column='CardID', on_delete=django.db.models.deletion.PROTECT, to='card.purchasedcard')),
                ('user_id', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
