# Generated by Django 4.1.4 on 2022-12-30 16:10

import card.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(db_column='Image', upload_to=card.models.Card.card_images_path)),
                ('min_amount', models.PositiveIntegerField(db_column='MinAmount')),
                ('max_amount', models.PositiveIntegerField(db_column='MaxAmount')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(db_column='Amount')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Confirmed')], db_column='State')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
                ('address_id', models.ForeignKey(db_column='AddressID', on_delete=django.db.models.deletion.PROTECT, to='user.address')),
                ('card_id', models.ForeignKey(db_column='CardID', on_delete=django.db.models.deletion.PROTECT, to='card.card')),
                ('user_id', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
