# Generated by Django 4.1.4 on 2022-12-30 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_column='PhoneNumber', max_length=31, unique=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=63, null=True)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=15, null=True)),
                ('is_banned', models.BooleanField(db_column='IsBanned', default=False)),
                ('is_male', models.BooleanField(blank=True, db_column='IsMale', null=True)),
                ('is_admin', models.BooleanField(db_column='IsAdmin', default=False)),
                ('birth_date', models.DateTimeField(blank=True, db_column='BirthDate', null=True)),
                ('last_login', models.DateTimeField(db_column='LastLogin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='DateJoined')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', default='', max_length=31)),
                ('address', models.CharField(db_column='Address', max_length=511)),
                ('latitude', models.CharField(db_column='Latitude', max_length=63)),
                ('longitude', models.CharField(db_column='Longitude', max_length=63)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('user_id', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
