name: Deployment

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt\


  deploy:
    - runs-on: ubuntu-latest
      steps:
        - name: Deploy to ${{ secrets.SSH_HOST }}
          uses: appleboy/ssh-action@master
          with:
            username: ${{ secrets.SSH_USERNAME }}
            host: ${{ secrets.SSH_HOST }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: 'cd /root/dev/btcgift && ./deploy.sh'