name: Initial Action

on:
  push:
    branches:
      - master

jobs:
  pip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          cache: pip

      - name: Install Requirements
        run: pip install -r requirements.txt
