name: Run pip

on:
  push:
    branches:
      - master

jobs:
  pip:
    runs-on: ubuntu-latest

    steps:
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements.txt
        run: pip install -r requirements.txt
